name: tdccm
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy>=1.24
  - pandas>=2.0
  - matplotlib>=3.6
  - seaborn>=0.12
  - pytest>=7.4
  - pip:
      - pyEDM @ git+https://github.com/SugiharaLab/pyEDM.git@bc7b850
